# Generated by Django 4.2.16 on 2024-12-12 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agri_match_app', '0002_operatorlisting_email_operatorlisting_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='agri_match_app.operatorlisting'),
        ),
    ]
