# Generated by Django 4.2.16 on 2024-12-08 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agri_match_app', '0002_remove_wishlist_operators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinerylisting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agri_match_app.machinerycategory'),
        ),
    ]
