# Generated by Django 4.2.16 on 2024-12-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_match_app', '0006_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(blank=True, to='agri_match_app.machinerylisting', verbose_name='Wishlist Items'),
        ),
    ]
